name: Compilar APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Probar nucleo Rust
        run: cd rust && cargo test --release

      - name: Instalar targets de Android
        run: rustup target add aarch64-linux-android armv7-linux-androideabi

      - name: Instalar cargo-ndk
        run: cargo install cargo-ndk

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compilar nucleo a .so (NDK)
        run: |
          cd rust
          cargo ndk -t arm64-v8a -t armeabi-v7a -o ../app/src/main/jniLibs build --release

      - name: Compilar APK
        run: |
          gradle wrapper
          ./gradlew assembleRelease --stacktrace

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: boveda-apk
          path: app/build/outputs/apk/release/*.apk
